[package]
name = "jjay"
version = "0.0.0"
authors = ["Fredrik Ã˜strem <frx.apps@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
serde = "1.0.114"
serde_json = "1.0.55"
